repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3

  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v8.47.0
  #   hooks:
  #     - id: eslint
  #       name: eslint
  #       language: node
  #       additional_dependencies:
  #         - eslint
  #         - "@eslint/js"
  #         - eslint-plugin-react
  #         - eslint-plugin-react-hooks
  #         - eslint-config-prettier
  #         - eslint-plugin-prettier
  #       entry: npx eslint frontend --ext .js,.jsx,.ts,.tsx --config frontend/eslint.config.cjs
  #       files: \.(js|jsx|ts|tsx|json|css|scss|md|html)$
